cmake -S . -B $PROJECT_ROOT/$BUILD_ROOT -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$PROJECT_ROOT/$WORKSPACE_ROOT
cmake --build $PROJECT_ROOT/$BUILD_ROOT --config $BUILD_TYPE
cmake --install $PROJECT_ROOT/$BUILD_ROOT --config $BUILD_TYPE
