#include <hardware/x86asm.hpp>
#include <hardware/x86gdt.hpp>
#include <hardware/x86call16.hpp>
#include <hardware/x86call16_stack.hpp>
#include <hardware/x86bios.hpp>
#include <hardware/bios_data_area.hpp>
#include <hardware/pic8259.hpp>
#include <hardware/rtccmos.hpp>
#include <hardware/kbdctrl.hpp>
#include <hardware/atwenty.hpp>
#include <hardware/console.hpp>
