find_program(CMAKE_C_COMPILER gcc-12)
set(CMAKE_C_COMPILER_ID GNU)
set(CMAKE_C_COMPILER_WORKS 1)


find_program(CMAKE_CXX_COMPILER g++-12)
set(CMAKE_CXX_COMPILER_ID GNU)
set(CMAKE_CXX_COMPILER_WORKS 1)
